### ISSUE TITLE
Half the game is outside the window

### ISSUE THREAD

**Issue by HlivaDenes** [aybe/dosbox-svn-daum#3]
This is a strange bug thats not happening in the original dosbox. 

If I launch dosbox-svn daum and drag and drop hocus.exe into it, it will have most of the game outside its window. I tried everything to solve it and nothing sensible would do. I even downloaded the steam version to check what was wrong with mine. That works. I replaced my gamefiles from the ones from steam. nothing. I replaced the dosbox files from the steam version. Still nothing. I tried to create a batch file to launch the game with a specific config, mimicking what the steam version does. It still fails. I then tried to check the config files i was launching compared to what the steam version uses. Same exact file character, for character. 

At this point, me being out of ideas completely, i decided to just put the dosbox folder into the game's folder, and launch it that way. Suddenly it works. Any idea why? Because even though I've managed to solve the issue i really have no fkin clue why its picky about changing folders in this specific way, and it would be nice if you could shine a light on it.

Here's some insight into the directories.

Steam's file structure: 
steamfolder\hocus pocus\hocus pocus\dosbox then the batch file goes into the dosbox folder launches the game, goes back up the tree by one, into the hocus game directory, and launches the config, and it works.

My original file structure: Retro Games\Dosbox, i launch the game from here, then i go to Retro Games\hocus, and drag and drop into dosbox. It cuts half the game off.

Working solution: Retro Games\hocus\DOSBOX. I launch dosbox, drag and drop the game exe into it, and it works.

As i said, the issue is fixed now, but i am just damn curious why this is happening. Do you have an idea why dosbox is so picky about which folder it decides to work from properly?

Sorry for bothering you with my stupid questions...

**Comment by aybe** [comment]
I have a rough idea ... dosbox has been written by many people piling things up over and over without real structuring, this resulted in lots of hacks and spaghetti code.

This fork is dead as well as original project is, so if I were you I'd do this:

- use https://github.com/joncampbell123/dosbox-x which is actively developed
- use original dosbox
- either with http://dfendreloaded.sourceforge.net/

I even suggest vanilla dosbox because while dosbox-x is actively developed, it has gone to a point where it doesn't even run some games out of the box without tweaking things, tweaking being absurdly complex because of the sheer amount of options in it, i.e. myself I use option 2/3 these days.

I've been committing quite a bit on x version, only to find out that over time things get broken because of no discipline about occasional committers on the project, extremely boring to redo what's already been done. That said, x project owner is serious and his support is on par too, you'll be in good hands if you go that road :)

Also, I learned that dosbox works best out of Program Files over time like in c:\dosbox, problem is, there is some stupid code that won't get fixed because it'll break something else (LMAO) along the fact that depending how you launch dosbox, sometimes it gets confused in paths like from taskbar etc, sometimes its current dir is SYSTEM32 which is utterly wrong but if you try to fix this code then some other code gets broken (hahahahahaha).

To have a good laugh just look at the code in repo, I bet that in less that 5 minutes you'll be OMG.

Hope that answers your question lol

**Comment by HlivaDenes** [comment]
Well, thank you for your answer, that was indeed enlightening. Also, why's this fork dead? It was cool, well, aside from this one bug.

**Comment by aybe** [comment]
well I guess he got bored over time, even Daum itself suggested switching to dosbox-x 😄
